Repository Pirates-of-Fife/oddity, pull requests merged in 2025-01, with the labels that each got.

#253 #169 alcubierre drive sounds
  Sounddesign/Alcubierre-Drive/Reaper/charging/Backups/charging-2025-01-02_122553.rpp-bak
  Sounddesign/Alcubierre-Drive/Reaper/charging/Backups/charging-2025-01-02_130024.rpp-bak
  Sounddesign/Alcubierre-Drive/Reaper/charging/Backups/charging-2025-01-03_083731.rpp-bak
  Sounddesign/Alcubierre-Drive/Reaper/charging/Media/659007__bigdino1995__chargeup.wav
  Sounddesign/Alcubierre-Drive/Reaper/charging/Media/peaks/659007__bigdino1995__chargeup.wav.reapeaks
  Sounddesign/Alcubierre-Drive/Reaper/charging/Media/peaks/sci-fi-weapon-charging-01-96645.mp3.reapeaks
  Sounddesign/Alcubierre-Drive/Reaper/charging/Media/sci-fi-weapon-charging-01-96645.mp3
  Sounddesign/Alcubierre-Drive/Reaper/charging/charging.rpp
  Sounddesign/Alcubierre-Drive/Reaper/entering/Media/explosion-under-snow-sfx-230505.mp3
  Sounddesign/Alcubierre-Drive/Reaper/entering/Media/peaks/explosion-under-snow-sfx-230505.mp3.reapeaks
  Sounddesign/Alcubierre-Drive/Reaper/entering/entering.rpp
  Sounddesign/Alcubierre-Drive/Reaper/leave/Backups/leave-2025-01-03_085436.rpp-bak
  Sounddesign/Alcubierre-Drive/Reaper/leave/Backups/leave-2025-01-03_090338.rpp-bak
  Sounddesign/Alcubierre-Drive/Reaper/leave/Backups/leave-2025-01-03_103658.rpp-bak
  Sounddesign/Alcubierre-Drive/Reaper/leave/Media/393374__evanboyerman__big-sci-fi-explosionbomb-close-mixed.wav
  Sounddesign/Alcubierre-Drive/Reaper/leave/Media/peaks/393374__evanboyerman__big-sci-fi-explosionbomb-close-mixed.wav.reapeaks
  Sounddesign/Alcubierre-Drive/Reaper/leave/Media/peaks/small-explosion-103779.mp3.reapeaks
  Sounddesign/Alcubierre-Drive/Reaper/leave/Media/small-explosion-103779.mp3
  Sounddesign/Alcubierre-Drive/Reaper/leave/leave.rpp
  Sounddesign/Alcubierre-Drive/Reaper/travelling/Backups/travelling-2025-01-03_103848.rpp-bak
  Sounddesign/Alcubierre-Drive/Reaper/travelling/Backups/travelling-2025-01-03_104715.rpp-bak
  Sounddesign/Alcubierre-Drive/Reaper/travelling/Backups/travelling-2025-01-03_104717.rpp-bak
  Sounddesign/Alcubierre-Drive/Reaper/travelling/Backups/travelling-2025-01-03_104719.rpp-bak
  Sounddesign/Alcubierre-Drive/Reaper/travelling/Backups/travelling-2025-01-03_104720.rpp-bak
  Sounddesign/Alcubierre-Drive/Reaper/travelling/Media/274186__littlerobotsoundfactory__spaceengine_controlroom_loop_01 (1).wav
  Sounddesign/Alcubierre-Drive/Reaper/travelling/Media/325808__soundjoao__motor-loop.wav
  Sounddesign/Alcubierre-Drive/Reaper/travelling/Media/peaks/274186__littlerobotsoundfactory__spaceengine_controlroom_loop_01 (1).wav.reapeaks
  Sounddesign/Alcubierre-Drive/Reaper/travelling/Media/peaks/325808__soundjoao__motor-loop.wav.reapeaks
  Sounddesign/Alcubierre-Drive/Reaper/travelling/travelling.rpp
  Sounddesign/Alcubierre-Drive/Render/charging/charging_end.wav
  Sounddesign/Alcubierre-Drive/Render/charging/charging_loop.wav
  Sounddesign/Alcubierre-Drive/Render/charging/charging_start.wav
  Sounddesign/Alcubierre-Drive/Render/entering/entering.wav
  Sounddesign/Alcubierre-Drive/Render/leave/leave.wav
  Sounddesign/Alcubierre-Drive/Render/travelling/travelling.wav
  Sounddesign/Alcubierre-Drive/Sample/274186__littlerobotsoundfactory__spaceengine_controlroom_loop_01 (1).wav
  Sounddesign/Alcubierre-Drive/Sample/274186__littlerobotsoundfactory__spaceengine_controlroom_loop_01.wav
  Sounddesign/Alcubierre-Drive/Sample/325808__soundjoao__motor-loop.wav
  Sounddesign/Alcubierre-Drive/Sample/393374__evanboyerman__big-sci-fi-explosionbomb-close-mixed.wav
  Sounddesign/Alcubierre-Drive/Sample/659007__bigdino1995__chargeup.wav
  Sounddesign/Alcubierre-Drive/Sample/explosion-under-snow-sfx-230505.mp3
  Sounddesign/Alcubierre-Drive/Sample/peaks/274186__littlerobotsoundfactory__spaceengine_controlroom_loop_01.wav.reapeaks
  Sounddesign/Alcubierre-Drive/Sample/peaks/659007__bigdino1995__chargeup.wav.reapeaks
  Sounddesign/Alcubierre-Drive/Sample/peaks/explosion-under-snow-sfx-230505.mp3.reapeaks
  Sounddesign/Alcubierre-Drive/Sample/peaks/small-explosion-103779.mp3.reapeaks
  Sounddesign/Alcubierre-Drive/Sample/sci-fi-weapon-charging-01-96645.mp3
  Sounddesign/Alcubierre-Drive/Sample/small-explosion-103779.mp3
Labels: sound

#246 shield bubble burst sound
  Sounddesign/power_off_sound/Reaper/Media/499072__16fpanskavyskocil_tom__pc-shut-down.wav
  Sounddesign/power_off_sound/Reaper/Media/peaks/499072__16fpanskavyskocil_tom__pc-shut-down.wav.reapeaks
  Sounddesign/power_off_sound/Reaper/shield_down.rpp
  Sounddesign/power_off_sound/Sample/499072__16fpanskavyskocil_tom__pc-shut-down.wav
  Sounddesign/power_off_sound/Sample/peaks/499072__16fpanskavyskocil_tom__pc-shut-down.wav.reapeaks
  Sounddesign/power_off_sound/power_off.wav
Labels: sound

#260 250 shields
  Artwork/Icons/ShieldAndHullUi/Shield.svg
  Artwork/Icons/ShieldAndHullUi/ShieldAndHullUi.ai
  Assets/Vehicles/Starships/Rabauke Shipworks/Kestrel Mk1/KestrelMk1.blend
  Assets/Vehicles/Starships/Rabauke Shipworks/Kestrel Mk1/KestrelMk1.blend1
  Assets/Vehicles/Starships/Rabauke Shipworks/Kestrel Mk1/KestrelMk1ShieldMesh.glb
  Game/oddity/classes/frame-of-reference/FrameOfReference.gd
  Game/oddity/classes/game-entity/GameEntity.gd
  Game/oddity/classes/module/Module.gd
  Game/oddity/classes/module/component/component-types/ShieldGenerator.gd
  Game/oddity/classes/module/component/component-types/shield/Shield.gd
  Game/oddity/classes/module/component/component-types/shield/ShieldHitSound.tscn
  Game/oddity/classes/module/component/component-types/shield/ShieldMaterial.tres
  Game/oddity/classes/module/component/component-types/shield/TestShield.tscn
  Game/oddity/classes/module/component/component-types/shield/shield_hit_sound.gd
  Game/oddity/classes/module/component/component-types/shield/sounds/shield_break-002.wav
  Game/oddity/classes/module/component/component-types/shield/sounds/shield_break-002.wav.import
  Game/oddity/classes/module/component/component-types/shield/sounds/shield_hit.wav
  Game/oddity/classes/module/component/component-types/shield/sounds/shield_hit.wav.import
  Game/oddity/classes/module/module-slot/ModuleSlot.gd
  Game/oddity/classes/multi-function-display/shield_and_hull_ui/HeartIcon.svg
  Game/oddity/classes/multi-function-display/shield_and_hull_ui/HeartIcon.svg.import
  Game/oddity/classes/multi-function-display/shield_and_hull_ui/ShieldAndHullUI.tscn
  Game/oddity/classes/multi-function-display/shield_and_hull_ui/ShieldAndHullUi.gd
  Game/oddity/classes/multi-function-display/shield_and_hull_ui/ShieldAndHullUi3D.gd
  Game/oddity/classes/multi-function-display/shield_and_hull_ui/ShieldAndHullUi3D.tscn
  Game/oddity/classes/multi-function-display/shield_and_hull_ui/ShieldIcon.svg
  Game/oddity/classes/multi-function-display/shield_and_hull_ui/ShieldIcon.svg.import
  Game/oddity/classes/projectile/Projectile.gd
  Game/oddity/classes/starship/Starship.gd
  Game/oddity/project.godot
  Game/oddity/resources/classes/module/component/shield-generator/ShieldGeneratorResource.gd
  Game/oddity/scenes/modules/rabauke_shipworks/thrusters/rabs-kestrel-mk-1/rcs-thruster/RABS_KestrelMk1_RcsThruster.tscn
  Game/oddity/scenes/modules/rabauke_shipworks/thrusters/rabs-kestrel-mk-1/retro-thruster/RABS_KestrelMk1_RetroThruster.tscn
  Game/oddity/scenes/modules/test-module/ShieldGenerator/ShieldGenerator.tscn
  Game/oddity/scenes/modules/test-module/ShieldGenerator/Size3Shield.tres
  Game/oddity/scenes/modules/test-module/ShieldGenerator/Size4Shield.tres
  Game/oddity/scenes/modules/test-module/ShieldGenerator/Size4ShieldGenerator.tscn
  Game/oddity/scenes/modules/test-module/Size5Weapon/Size5Weapon.tscn
  Game/oddity/scenes/modules/test-module/Size5Weapon/Size5WeaponResource.tres
  Game/oddity/scenes/modules/test-module/Size6Weapon/LaserProjectile.tscn
  Game/oddity/scenes/modules/test-module/Size6Weapon/Size6Weapon.tscn
  Game/oddity/scenes/modules/test-module/Size6Weapon/Size6WeaponResource.tres
  Game/oddity/scenes/vehicles/starships/rabauke-shipworks/kestrel-mk-1/RABS_KestrelMk1.gd
  Game/oddity/scenes/vehicles/starships/rabauke-shipworks/kestrel-mk-1/RABS_KestrelMk1.tscn
  Game/oddity/scenes/vehicles/starships/rabauke-shipworks/kestrel-mk-1/meshes/KestrelMk1ShieldMesh.glb
  Game/oddity/scenes/vehicles/starships/rabauke-shipworks/kestrel-mk-1/meshes/KestrelMk1ShieldMesh.glb.import
  Game/oddity/test-scenes/star-system-test-scene/StarSystemTestScene.tscn
  Game/oddity/test-scenes/star-system-test-scene/starshipTestShoot.gd
Labels: feature, module

#262 259-starship power off
  Sounddesign/starship_power_off/Reaper/Backups/Starship_power_off-2025-01-04_104428.rpp-bak
  Sounddesign/starship_power_off/Reaper/Media/peaks/shield_down.wav.reapeaks
  Sounddesign/starship_power_off/Reaper/Media/shield_down.wav
  Sounddesign/starship_power_off/Reaper/Starship_power_off.rpp
  Sounddesign/starship_power_off/peaks/shield_down.wav.reapeaks
  Sounddesign/starship_power_off/shield_down.wav
  Sounddesign/starship_power_off/starship_power_off.wav
Labels: feature, sound

#270 190 enemy ai
  Game/oddity/classes/abyss/abyssal-tunnel/AbyssalTunnelMaterial.tres
  Game/oddity/classes/controller/ai-controller/AiController.gd
  Game/oddity/classes/controller/ai-controller/ai-vehicle-controller/AiVehicleController.gd
  Game/oddity/classes/controller/ai-controller/ai-vehicle-controller/ai-starship-controller/AiStarshipController.gd
  Game/oddity/classes/controller/ai-controller/ai-vehicle-controller/ai-starship-controller/AiStarshipController.tscn
  Game/oddity/classes/controller/controller.gd
  Game/oddity/classes/controller/vehicle-controller/starship-controller/StarshipController.gd
  Game/oddity/classes/creature/Creature.tscn
  Game/oddity/classes/creature/humanoid/Humanoid.tscn
  Game/oddity/classes/game-entity/control-entity/ControlEntity.gd
  Game/oddity/classes/interactable/control-seat/ControlSeat.gd
  Game/oddity/classes/mind/Mind.gd
  Game/oddity/classes/mind/ai/Ai.gd
  Game/oddity/classes/mind/ai/Ai.tscn
  Game/oddity/classes/mind/player/anchor/Anchor.tscn
  Game/oddity/classes/mind/player/anchor/anchor.gd
  Game/oddity/classes/mind/player/anchor/icons/Anchor.svg
  Game/oddity/classes/mind/player/anchor/icons/Anchor.svg.import
  Game/oddity/classes/mind/player/player.gd
  Game/oddity/classes/mind/player/player.tscn
  Game/oddity/classes/player/anchor/icons/Anchor.svg
  Game/oddity/classes/player/anchor/icons/Anchor.svg.import
  Game/oddity/classes/player/player.gd
  Game/oddity/classes/projectile/Projectile.gd
  Game/oddity/classes/starship/Starship.gd
  Game/oddity/project.godot
  Game/oddity/resources/classes/vehicle/starship/StarshipInfo.gd
  Game/oddity/scenes/environment/fire/BigFire.tscn
  Game/oddity/scenes/environment/fire/Fire.tscn
  Game/oddity/scenes/interactable/control-seat/DemoControlSeat.tscn
  Game/oddity/scenes/modules/test-module/ShieldGenerator/Size3Shield.tres
  Game/oddity/scenes/modules/test-module/ShieldGenerator/Size4Shield.tres
  Game/oddity/scenes/modules/test-module/Size5Weapon/LaserProjectile.tscn
  Game/oddity/scenes/modules/test-module/Size5Weapon/Size5Weapon.tscn
  Game/oddity/scenes/modules/test-module/Size5Weapon/Size5WeaponResource.tres
  Game/oddity/scenes/modules/test-module/Size6Weapon/LaserProjectile.tscn
  Game/oddity/scenes/modules/test-module/Size6Weapon/LaserProjectileHitSound.tscn
  Game/oddity/scenes/modules/test-module/Size6Weapon/ProjectileHitPartcle.tscn
  Game/oddity/scenes/modules/test-module/Size6Weapon/Size6Weapon.tscn
  Game/oddity/scenes/modules/test-module/Size6Weapon/Size6WeaponResource.tres
  Game/oddity/scenes/vehicles/starships/demo-ship-2/DemoShip2.tscn
  Game/oddity/scenes/vehicles/starships/demo-ship/DemoShip.tscn
  Game/oddity/scenes/vehicles/starships/rabauke-shipworks/common/scenes/seats/RABS_ControlSeat.tscn
  Game/oddity/scenes/vehicles/starships/rabauke-shipworks/kestrel-mk-1/RABS_KestrelMk1.gd
  Game/oddity/scenes/vehicles/starships/rabauke-shipworks/kestrel-mk-1/RABS_KestrelMk1.tscn
  Game/oddity/scenes/vehicles/starships/rabauke-shipworks/kestrel-mk-1/resources/RABS_KestrelMk1_Info.tres
  Game/oddity/scenes/vehicles/starships/rabauke-shipworks/kestrel-mk-1/resources/RABS_KestrelMk1_Thruster.tres
  Game/oddity/test-scenes/basic-player-test-scene/BasicPlayerTest.tscn
  Game/oddity/test-scenes/command-architecture-test-scene/CommandArchitectureTest.tscn
  Game/oddity/test-scenes/module-test-scene/ModuleTestScene.tscn
  Game/oddity/test-scenes/ship-test-scene/ShipTestScene.tscn
  Game/oddity/test-scenes/star-system-test-scene/StarSystemTestScene.tscn
  Game/oddity/test-scenes/star-system-test-scene/luna_cube.gd
Labels: feature

#273 271 mouse sensitivity option
  Game/oddity/classes/controller/creature-controller/CreatureController.gd
  Game/oddity/classes/controller/vehicle-controller/starship-controller/StarshipController.gd
  Game/oddity/classes/mind/player/CreditHud.tscn
  Game/oddity/classes/mind/player/credit_hud.gd
  Game/oddity/classes/mind/player/player.gd
  Game/oddity/classes/mind/player/player.tscn
  Game/oddity/globals/globals.gd
  Game/oddity/project.godot
  Game/oddity/scenes/vehicles/starships/rabauke-shipworks/kestrel-mk-1/RABS_KestrelMk1.gd
  Game/oddity/ui/main-menu/MainMenu.tscn
  Game/oddity/ui/main-menu/MainMenuUI.tscn
  Game/oddity/ui/main-menu/main_menu.gd
Labels: feature

#279 278 hardpoint enhancements
  Artwork/UI/Hardpoint Assignment Screen/O.svg
  Artwork/UI/Hardpoint Assignment Screen/ShipOutline.ai
  Artwork/UI/Hardpoint Assignment Screen/ShipOutline.svg
  Game/oddity/classes/command/vehicle-commands/starship-commands/StarshipShootTertiaryCommand.gd
  Game/oddity/classes/command/vehicle-commands/starship-commands/StarshipStopShootingPrimaryCommand.gd
  Game/oddity/classes/command/vehicle-commands/starship-commands/StarshipStopShootingSecondaryCommand.gd
  Game/oddity/classes/command/vehicle-commands/starship-commands/StarshipStopShootingTertiaryCommand.gd
  Game/oddity/classes/controller/ai-controller/ai-vehicle-controller/ai-starship-controller/AiStarshipController.gd
  Game/oddity/classes/controller/vehicle-controller/starship-controller/StarshipController.gd
  Game/oddity/classes/module/module-slot/dynamic-module-slot/hardpoint/Hardpoint.gd
  Game/oddity/classes/module/weapon/BeamWeapon.gd
  Game/oddity/classes/module/weapon/MiningLaser.gd
  Game/oddity/classes/module/weapon/ProjectileWeapon.gd
  Game/oddity/classes/module/weapon/Weapon.gd
  Game/oddity/classes/multi-function-display/hardpoint-assignment-screen/AssignmentButton.gd
  Game/oddity/classes/multi-function-display/hardpoint-assignment-screen/AssignmentButton.tscn
  Game/oddity/classes/multi-function-display/hardpoint-assignment-screen/AssignmentButtonMaterialDefault.tres
  Game/oddity/classes/multi-function-display/hardpoint-assignment-screen/AssignmentButtonMaterialSelected.tres
  Game/oddity/classes/multi-function-display/hardpoint-assignment-screen/HardpointASsignmentDisplay.tscn
  Game/oddity/classes/multi-function-display/hardpoint-assignment-screen/O.svg
  Game/oddity/classes/multi-function-display/hardpoint-assignment-screen/O.svg.import
  Game/oddity/classes/multi-function-display/hardpoint-assignment-screen/ShipOutline.svg
  Game/oddity/classes/multi-function-display/hardpoint-assignment-screen/ShipOutline.svg.import
  Game/oddity/classes/multi-function-display/hardpoint-assignment-screen/ShipOutlineSelectionUi.tscn
  Game/oddity/classes/starship/Starship.gd
  Game/oddity/project.godot
  Game/oddity/scenes/modules/test-module/Size5Weapon/Size5Weapon.tscn
  Game/oddity/scenes/modules/test-module/Size6Weapon/Size6Weapon.tscn
  Game/oddity/scenes/vehicles/starships/rabauke-shipworks/kestrel-mk-1/RABS_KestrelMk1.tscn
  Game/oddity/test-scenes/star-system-test-scene/StarSystemTestScene.tscn
Labels: feature, ui

#291 woooo saving and loading
  Game/oddity/classes/landing-pad/save-ship-ui/save_ship_ui.gd
  Game/oddity/classes/landing-pad/spawn-ship-ui/SpawnShipUi.tscn
  Game/oddity/classes/landing-pad/spawn-ship-ui/spawn_ship_ui.gd
  Game/oddity/classes/module/module-slot/ModuleSlot.gd
  Game/oddity/classes/module/module-slot/dynamic-module-slot/DynamicModuleSlot.gd
  Game/oddity/classes/module/module-slot/dynamic-module-slot/hardpoint/ExternalHardpoint.gd
  Game/oddity/classes/starship/Starship.gd
  Game/oddity/resources/classes/vehicle/starship/starship-loadout/LoadoutGenerator.gd
  Game/oddity/resources/classes/vehicle/starship/starship-loadout/ModuleSlotLoadoutResource.gd
  Game/oddity/resources/classes/vehicle/starship/starship-loadout/StarshipLoadout.gd
  Game/oddity/resources/classes/vehicle/starship/starship-loadout/Test.tscn
  Game/oddity/resources/classes/vehicle/starship/starship-loadout/module-slots/AbyssalJumpDriveSlotLoadoutResource.gd
  Game/oddity/resources/classes/vehicle/starship/starship-loadout/module-slots/AlcubierreDriveSlotLoadoutResource.gd
  Game/oddity/resources/classes/vehicle/starship/starship-loadout/module-slots/ComponentSlotLoadoutResource.gd
  Game/oddity/resources/classes/vehicle/starship/starship-loadout/module-slots/HardpointLoudoutResource.gd
  Game/oddity/resources/classes/vehicle/starship/starship-loadout/module-slots/ThrusterSlotLoadoutResource.gd
  Game/oddity/resources/classes/vehicle/starship/starship-loadout/module-slots/new_resource.tres
  Game/oddity/scenes/cargo/cargo-selling-ui/CargoSellingTestArea.tscn
  Game/oddity/scenes/vehicles/starships/rabauke-shipworks/kestrel-mk-1/RABS_KestrelMk1.tscn
  Game/oddity/scenes/vehicles/starships/rabauke-shipworks/kestrel-mk-1/resources/RABS_Kestrel_MK1_Default_Loadout.tres
  Game/oddity/scenes/vehicles/starships/rabauke-shipworks/kestrel-mk-1/resources/RABS_Kestrel_MK1_Loadout_Layout.tres
Labels: feature

#293 fixed bugs
  Game/oddity/classes/landing-pad/repair-ui/RepairUi2d.tscn
  Game/oddity/classes/landing-pad/save-ship-ui/SaveShipUi2d.tscn
  Game/oddity/classes/landing-pad/spawn-ship-ui/SpawnShipUi2d.tscn
  Game/oddity/resources/classes/vehicle/starship/starship-loadout/LoadoutGenerator.gd
  Game/oddity/resources/classes/vehicle/starship/starship-loadout/Test.tscn
  Game/oddity/resources/classes/vehicle/starship/starship-loadout/module-slots/RadiatorSlotLoadoutResource.gd
  Game/oddity/scenes/modules/rabauke_shipworks/radiators/rabs-kestrel-mk-1/RABS_KestrelMk1_LeftRadiatorSlot.tscn
  Game/oddity/scenes/modules/rabauke_shipworks/radiators/rabs-kestrel-mk-1/RABS_KestrelMk1_RightRadiatorSlot.tscn
  Game/oddity/scenes/vehicles/starships/rabauke-shipworks/kestrel-mk-1/RABS_KestrelMk1.tscn
  Game/oddity/scenes/vehicles/starships/rabauke-shipworks/kestrel-mk-1/resources/RABS_Kestrel_MK1_Default_Loadout.tres
  Game/oddity/scenes/vehicles/starships/rabauke-shipworks/kestrel-mk-1/resources/RABS_Kestrel_MK1_Loadout_Layout.tres
  Game/oddity/test-scenes/star-system-test-scene/StarSystemTestScene.tscn
Labels: bug

#297 295 save cargo objects and other things in loadout files
  Game/oddity/classes/cargo/CargoGrid.gd
  Game/oddity/classes/starship/Starship.gd
  Game/oddity/resources/classes/vehicle/starship/starship-loadout/LoadoutGenerator.gd
  Game/oddity/resources/classes/vehicle/starship/starship-loadout/StarshipLoadout.gd
  Game/oddity/resources/classes/vehicle/starship/starship-loadout/Test.tscn
  Game/oddity/resources/classes/vehicle/starship/starship-loadout/cargo/CargoContainerLoadoutResource.gd
  Game/oddity/resources/classes/vehicle/starship/starship-loadout/objects/GameEntityLoadoutResource.gd
  Game/oddity/scenes/cargo/cargo-containers/Cu1Container.tscn
  Game/oddity/scenes/cargo/cargo-selling-ui/CargoSellingTestArea.tscn
  Game/oddity/scenes/vehicles/starships/rabauke-shipworks/kestrel-mk-1/RABS_KestrelMk1.tscn
  Game/oddity/scenes/vehicles/starships/rabauke-shipworks/kestrel-mk-1/resources/RABS_Kestrel_MK1_Default_Loadout.tres
  Game/oddity/test-scenes/star-system-test-scene/StarSystemTestScene.tscn
Labels: feature

#298 added hull reinforcements
  Game/oddity/classes/module/component/component-types/HullReinforcement.gd
  Game/oddity/classes/module/component/component-types/shield/Shield.gd
  Game/oddity/classes/starship/Starship.gd
  Game/oddity/resources/classes/module/component/hull-reinforcement/HullReinforcementResource.gd
  Game/oddity/scenes/modules/test-module/hull-reinforcement/size-1/Size1HullReinforcement.tres
  Game/oddity/scenes/modules/test-module/hull-reinforcement/size-1/Size1HullReinforcement.tscn
  Game/oddity/scenes/modules/test-module/hull-reinforcement/size-2/Size2HullReinforcement.tres
  Game/oddity/scenes/modules/test-module/hull-reinforcement/size-2/Size2HullReinforcement.tscn
  Game/oddity/scenes/modules/test-module/hull-reinforcement/size-3/Size3HullReinforcement.tres
  Game/oddity/scenes/modules/test-module/hull-reinforcement/size-3/Size3HullReinforcement.tscn
  Game/oddity/scenes/modules/test-module/hull-reinforcement/size-4/Size4HullReinforcement.tres
  Game/oddity/scenes/modules/test-module/hull-reinforcement/size-4/Size4HullReinforcement.tscn
  Game/oddity/scenes/vehicles/starships/rabauke-shipworks/kestrel-mk-1/RABS_KestrelMk1.tscn
  Game/oddity/scenes/vehicles/starships/rabauke-shipworks/kestrel-mk-1/resources/RABS_Kestrel_MK1_Default_Loadout.tres
Labels: feature, module
