Repository Pirates-of-Fife/oddity, pull requests merged in 2025-02, with the labels that each got.

#310 240-simple-space-station
  Assets/SpaceStation/big_wheel.glb
  Assets/SpaceStation/house.glb
  Assets/SpaceStation/interior.glb
  Assets/SpaceStation/small_wheel.glb
  Assets/SpaceStation/space_station.blend
  Assets/SpaceStation/space_station.blend1
  Assets/SpaceStation/space_station.glb
Labels: feature, modelling

#313 284-hull-reinforcement-module-model
  Assets/Hull_Reinforcement/hullReinforcementModule.blend
  Assets/Hull_Reinforcement/hullReinforcementModule.blend1
  Assets/Hull_Reinforcement/hullReinforcementModule.glb
Labels: feature, modelling, module

#340 charaktercrazy
  Game/oddity/classes/character_model/Character Base Color.png
  Game/oddity/classes/character_model/Character Base Color.png.import
  Game/oddity/classes/character_model/charakter.bin
  Game/oddity/classes/character_model/charakter.glb
  Game/oddity/classes/character_model/charakter.glb.import
  Game/oddity/classes/character_model/charakter.gltf
  Game/oddity/classes/character_model/charakter.gltf.import
  Game/oddity/classes/character_model/charakter_Character Base Color.png
  Game/oddity/classes/character_model/charakter_Character Base Color.png.import
  Game/oddity/classes/station/station_landing_pad/StationPad.tscn
Labels: modelling, animation
